fieldtype_fields:
  max_items:
    type: text
  sort:
    type: text
    width: 50
  label:
    type: text
    width: 50
  collection:
    type: collections
    width: 50
  mode:
    type: select
    width: 50
    options:
      tags: Tags
      panes: Panes
