fieldtype_fields:
  buttons:
    type: bard_buttons_setting
    display: Buttons
    default:
      - h2
      - h3
      - bold
      - italic
      - unorderedlist
      - orderedlist
      - removeformat
      - quote
      - anchor
  style:
    type: radio
    default: sans
    options:
      sans: Github (sans-serif)
      serif: A book (serif)
    width: 50
  spellcheck:
    type: toggle
    default: true
    width: 50
  allow_source:
    type: toggle
    default: true
    width: 50
  allow_internal_links:
    type: toggle
    default: true
    width: 50
  link_noopener:
    type: toggle
    default: false
    width: 50
  link_noreferrer:
    type: toggle
    default: false
    width: 50
  target_blank:
    type: toggle
    default: false
    width: 50
  semantic_elements:
    type: toggle
    default: false
    width: 50
  container:
    type: asset_container
    allow_blank: true
  folder:
    type: asset_folder
    width: 50
  restrict_assets:
    type: toggle
    width: 50
  sets:
    type: replicator_sets
