fieldtype_fields:
  settings:
    type: redactor_settings
  container:
    type: asset_container
    allow_blank: true
  folder:
    type: asset_folder
    width: 50
  restrict_assets:
    type: toggle
    width: 50
