fieldtype_fields:
  allow_blank:
    type: toggle
  allow_time:
    type: toggle
    default: true
    width: 50
  require_time:
    type: toggle
    default: false
    width: 50
  earliest_date:
    type: text
    default: January 1, 1900
  format:
    type: text
    width: 50
  input_format:
    type: text
    width: 50
