routes:
  /feed:
    layout: feed
    template: feeds/articles
    content_type: atom
  /feed/atom:
    layout: feed
    template: feeds/articles
    content_type: atom
collections:
  articles: '/{slug}'
taxonomies: '{  }'
redirect:
  /ladder: freedom
  /im-a-fcking-webmaster: webmaster
  /sideproject: bootstrap-side-project
